### ISSUE TITLE
Feature Request: Crop & Rotation

### ISSUE THREAD

**Issue by noxhirsch** [TheLastProject/lovelace-valetudo-map-card#1]
Hi, thank you for this amazing lovelace card!
Is it possible to add the crop function? https://github.com/Hypfer/ICantBelieveItsNotValetudo/issues/7 => https://github.com/Hypfer/ICantBelieveItsNotValetudo/pull/8 
Also rotation would be amazing!
With both of these functions, the map can be integrated very space efficient :)

Thank you in advance!

**Comment by TheLastProject** [comment]
Rotation seems much easier to implement in CSS3 so I'll probably get to that first. I'll have to think a bit on how to best tackle the cropping thing in my implementation, but it definitely sounds doable to add

**Comment by TheLastProject** [comment]
Rotation support was added in 3d6343c635efb2326369df823e915ed93a0c6e99

**Comment by noxhirsch** [comment]
Thank you very much!
I noticed an issue with the rotation:
![InkedScreenshot (4)_LI](https://user-images.githubusercontent.com/30938717/63613669-8e773000-c5e1-11e9-8f58-a6f87149b68f.jpg)
When the card is rotated, the height of the card stays the same, because of which I get bigger padding in the top and bottom.
(I also have `map_scale: 1.5`, if that matters)

**Comment by TheLastProject** [comment]
Basic cropping was added in f122fe987477d444017641b09a8dc0351354b8f6.

I'll take a look at the rotation issue soon, thanks!

**Comment by TheLastProject** [comment]
I hope 1d45c813f3813aa1652f19cdd0ee41a0b595bdf4 mitigates the rotation issue. If it doesn't, I'm going to have to tag this issue with "help wanted". I don't normally develop webpages so my HTML/CSS/JavaScript is quite rusty :)

**Comment by noxhirsch** [comment]
Wow, you're fast! 😄 
Quick feedback: The cropping itself works flawless! The only issue is, that the map keeps the same size and position. So as you can see in the picture above, the map is more on the right side (especially now after cropping my balcony in the lower left corner away). It would be perfect, if the lovelace card fits exactly to the cropped map size (so that there's minimal to no padding between the cropped map and the lovelace card border)

---------------

The rotation got very weird now: `rotation: 0` & `rotation: 90` does look the same (original orientation). To rotate it to 90° I had to use `rotation: 45` - and the weirdest thing: After that I got a scrollbar for the whole lovelace card column:
![issue_2](https://user-images.githubusercontent.com/30938717/63616694-6a6b1d00-c5e8-11e9-992d-3c78382f35e7.PNG)

I can take a look and try to help - but my development skills are rudimentary in general ;)

**Comment by TheLastProject** [comment]
>Quick feedback: The cropping itself works flawless! The only issue is, that the map keeps the same size and position. So as you can see in the picture above, the map is more on the right side (especially now after cropping my balcony in the lower left corner away). It would be perfect, if the lovelace card fits exactly to the cropped map size (so that there's minimal to no padding between the cropped map and the lovelace card border)

Yup, I've been lazy there, I'll take a better look at that later. Release early, release often and all :)

>The rotation got very weird now: rotation: 0 & rotation: 90 does look the same (original orientation). To rotate it to 90° I had to use rotation: 45 - and the weirdest thing: After that I got a scrollbar for the whole lovelace card column

Not sure what caused the scrollbar, but the rotation should be fixed again in e546cbe412b91c961a3bdef454f17bbb53d85799, whoops.

**Comment by noxhirsch** [comment]
I think I found the problem (can't test it right now):
You have two selectors: `div` and `div div`. The latter selects a div container inside a div container - but the first one selects the outer and the inner div and doubles the effect.

**Comment by noxhirsch** [comment]
You were faster :D I test it in 20 minutes!

**Comment by noxhirsch** [comment]
Now the new issues are gone, but the card height stays the same as before :/

Brainstorming: I want to propose a different approach -  what about let the user set a fixed aspect ration like in the map card (e.g. 3:2). Then there's `rotation`, `left_offset`, `right_offset` (which are already in your code, as I can see) & `scale` with which the user can move and resize the map inside the canvas to make it fit.
If you don't like the idea (or think it's not viable) just ignore it ;)

**Comment by TheLastProject** [comment]
Sounds quite complex, I'm hoping for something simpler honestly. It's probably just some small overflow issue I can easily fix with some CSS once I remember the right statements.

The offset is a different thing though, it's for translating the position of the vacuum and dock to the map because it uses another metric ("points" instead of pixels).

I'm sure it'll be fixed nicely at some point, either by me remembering how or by someone else making a pull request :)

**Comment by TheLastProject** [comment]
I created a https://github.com/TheLastProject/lovelace-valetudo-map-card/tree/fix/sizing branch, which makes cropping behave right about perfectly. However, when combined with rotation, things are even worse than before and cropping behaves very strangely. I'm afraid some other person will have to come along to fix this all.

**Comment by TheLastProject** [comment]
Ehh, I'll just commit it to master I guess and make a new issue.
