### ISSUE TITLE
Entity not available: camera.map_data

### ISSUE THREAD

**Issue by wimb0** [TheLastProject/lovelace-valetudo-map-card#101]
Since updating my Roborock S5 to Valetudo 2021.11, the integration gives me `Entity not available: camera.map_data`
Rebooting server or vacuum does not help.
Clearing cache or using fresh browser does not help.
Tested also different Lovelace configs for the card, still no go...

![image](https://user-images.githubusercontent.com/11030068/141130116-58957674-e5a1-4b3f-b04b-b2aa0f991ab2.png)

The camera.map_data has data in MQTT (checked with mqtt-explorer), and is accessible in Home Assistant.

I'm Using:
- Home Assistant 2021.11.2
- Valetudo 2021.11
- Valetudo Map Card v2021-08-12 via HACS

Any ideas or is this a bug?

**Comment by TheLastProject** [comment]
What does your MQTT config like for your vacuum? And what is camera.map_data looking like?

![image](https://user-images.githubusercontent.com/1885159/141151820-0ce15780-9ff3-4834-8c2b-f09ed3ba2160.png)

**Comment by wimb0** [comment]
MQTT settings for the vacuum in Home Assistant:
![image](https://user-images.githubusercontent.com/11030068/141152231-4d016e69-4557-4488-869b-96cde65adc83.png)

MQTT settings in Valetudo:
![image](https://user-images.githubusercontent.com/11030068/141153262-d2d56d05-ea0c-482d-a247-201dd23c69fd.png)

camera.map_data image just shows the use this card message.
Map data:
![image](https://user-images.githubusercontent.com/11030068/141153553-c7cc5d41-4313-4b83-b888-f8c0182fa5a8.png)

**Comment by TheLastProject** [comment]
Anything in the browser console when on the screen that contains this card?

**Comment by wimb0** [comment]
Nothing special:
![image](https://user-images.githubusercontent.com/11030068/141155702-05418b1a-890f-4021-aad3-762cb07f1dfb.png)

**Comment by TheLastProject** [comment]
What's your card config?

**Comment by wimb0** [comment]
```
type: custom:valetudo-map-card
entity: camera.map_data
vacuum_entity: vacuum.kees
rotate: 0
crop:
  top: 0
  bottom: 0
  left: 0
  right: 0
min_height: 0
```

**Comment by TheLastProject** [comment]
Hmm... that should be correct. No clue why it's not working.

Only thing I'm noticing is that I'm on Home Assistant 2021.11.0 myself, I'll try to update Home Assistant just to check if they broke something again.

**Comment by TheLastProject** [comment]
Hmm, nope, it still works for me. I really have no clue then :( Maybe try the Valetudo Telegram channel? Maybe someone there has a smart idea :(

**Comment by wimb0** [comment]
No problem, I'll try to troubleshoot some more. Thanks for the quick responses. :-)

**Comment by wimb0** [comment]
Fixed! Seems to have been a problem on my side:
Wanted to reinstall the add-on one more time to start fresh while troubleshooting.
HACS said that it uninstalled it, but I found that the files were still in `/config/www/community/`, so I rm -r'ed them from disk.
Reinstalled via HACS, hit CTRL-F5, and voila, card works...

No idea on how or why, but it is solved.
