### ISSUE TITLE
How to install it with HACS?

### ISSUE THREAD

**Issue by DangerD1024** [TheLastProject/lovelace-valetudo-map-card#104]
Tried to add custom repository, it says that it's already added
In HACS integrations/UI i don't see valetudo map card...
![image](https://user-images.githubusercontent.com/4560434/147383925-8fc34610-55d2-4fb6-864f-1eb79be84f0a.png)

Installed it manually by uploading js file...

**Comment by TheLastProject** [comment]
It is part of the main HACS repo, so you don't need to add an extra repo.

No clue why it doesn't show up for you though, it works fine for me. Maybe a bug in HACS? Sorry can't help you there.
