### ISSUE TITLE
Aspect Ratio

### ISSUE THREAD

**Issue by xMrVizzy** [TheLastProject/lovelace-valetudo-map-card#11]
Please add aspect ratio support for card like a picture card using camera! I need it to set final card size so that it does not change after cropping the map

**Comment by TheLastProject** [comment]
Could you explain how you feel this should work? Like a configuration example too? I can't really imagine how this would work and why it would be useful. Or are you just looking to be able to set a fixed width and height?

**Comment by xMrVizzy** [comment]
Yes fixed height of map!
I fit Vacuum Map to Camera Aspect ratio 16x9 on mobile, but on other devices its not resize it keeps map height, see screenshots:

<img width="1184" alt="CleanShot 2019-09-27 at 01 21 22@2x" src="https://user-images.githubusercontent.com/7906418/65722234-4c03b000-e0c5-11e9-9736-93dae526262c.png">
<img width="1181" alt="CleanShot 2019-09-27 at 01 22 56@2x" src="https://user-images.githubusercontent.com/7906418/65722257-59b93580-e0c5-11e9-8c57-6ceb3af4ee29.png">
<img width="1184" alt="CleanShot 2019-09-27 at 01 23 13@2x" src="https://user-images.githubusercontent.com/7906418/65722278-65a4f780-e0c5-11e9-9854-cf838cec362a.png">

**Comment by xMrVizzy** [comment]
I mean aspect ratio is fixed height width for card, map image crop under card frame.
Aspect ratio should change size of card frame not a map!

**Comment by xMrVizzy** [comment]
If you not understand what I mean I can send more examples!

**Comment by xMrVizzy** [comment]
https://www.home-assistant.io/lovelace/picture-entity/
<img width="684" alt="CleanShot 2019-09-27 at 01 28 09@2x" src="https://user-images.githubusercontent.com/7906418/65722655-190dec00-e0c6-11e9-9b6e-42ebc5ca7e4a.png">

**Comment by TheLastProject** [comment]
Hmm, how about I implement something like this?

Height hardcoded to 200px always:
```
type: 'custom:valetudo-map-card'
entity: sensor.xiaomi_map
height: 200
```

Height being 1.5 times the width:
```
type: 'custom:valetudo-map-card'
entity: sensor.xiaomi_map
height: 1.5w
```

Would that be what you're looking for?

**Comment by TheLastProject** [comment]
I believe the latest release should fix your issue, try setting `min_height: 1.78` on it (which is 16x9)

**Comment by xMrVizzy** [comment]
Its not working correct but I find a way!

Right 16x9 picture (for compare with yours):
<img width="1182" alt="CleanShot 2019-09-28 at 15 02 12@2x" src="https://user-images.githubusercontent.com/7906418/65814862-077d2f00-e201-11e9-9836-866d991a8cad.png">

If I set min_height: 1.78 its makes this:
<img width="1181" alt="CleanShot 2019-09-28 at 15 03 17@2x" src="https://user-images.githubusercontent.com/7906418/65814872-1ebc1c80-e201-11e9-9bd5-25c941aa31d8.png">

If I set min_height: 1.78w its also not work and makes: height = width + 0.78width
<img width="1183" alt="CleanShot 2019-09-28 at 15 05 08@2x" src="https://user-images.githubusercontent.com/7906418/65814892-62168b00-e201-11e9-84af-41dc27e6203f.png">

I thinking if it should be in width 16 and in height 9, I should: 9/16 = 0.5625w, and it is a right way I can make it work:
<img width="1182" alt="CleanShot 2019-09-28 at 15 13 25@2x" src="https://user-images.githubusercontent.com/7906418/65814971-8aeb5000-e202-11e9-9ba2-94555771307c.png">

Its work, but it isn't 16x9 value is 9x16 you should invert logic of calculations to use simply 1.78w and other standard values I think! You should fix height = width*1.78 to: height = width/1.78

**Comment by xMrVizzy** [comment]
And also how to add border-radius for card now? Previously it was:
ha-card {
                border-radius: var(--border-radius);
              }

now it doesn't work because? any suggestions how to add it to card (border-radius applying to card when its loading, when map appear borders already square)

**Comment by TheLastProject** [comment]
Looking at my Home Assistant installation, just having `--ha-card-border-radius` set in your theme should still work.

**Comment by xMrVizzy** [comment]
Okay, Thank you for your work!

**Comment by TheLastProject** [comment]
Thank you for your patience and help testing :)
