### ISSUE TITLE
Suggestion for installation readme

### ISSUE THREAD

**Issue by alve89** [TheLastProject/lovelace-valetudo-map-card#111]
After I struggled almost a day with including my Valetudo map to Home Assistant, here's a short suggestions. You could add to the installation description, that the name must
- likely start with `valetudo_` **even if a user-configured machine-readable identifier was set up**
- likely be lowercase, even if the set up machine-readable identifier is in camelcase. 

Perhaps this could save some time for other users...

That's it. And at the end: Great job!

**Comment by TheLastProject** [comment]
Could you elaborate on what you mean with "a user-configured machine-readable identifier"?

**Comment by alve89** [comment]
Sure, here are some screenshots from Valetudo, the last one is from Home Assistant.

That's the generic identifier:
![image](https://user-images.githubusercontent.com/11487054/148185149-dd5def5e-0811-4622-9a92-b46c26241986.png)

That's the one I set up (that's what I meant with `a user-configured machine-readable identifier`):
![image](https://user-images.githubusercontent.com/11487054/148184985-dea60922-b909-4055-b575-f96d22da0716.png)

One needs to use this one in lowercase:
![image](https://user-images.githubusercontent.com/11487054/148185306-46adfc45-e698-4af9-8345-1cb061f90709.png)

**Comment by TheLastProject** [comment]
I think this should help: https://github.com/TheLastProject/lovelace-valetudo-map-card/commit/068f223aeb70c2244134c172ace8591dea30a30a?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

If not, feel free to comment and I'll reopen and we can discuss this further.
