### ISSUE TITLE
Map does not show up

### ISSUE THREAD

**Issue by mxwi** [TheLastProject/lovelace-valetudo-map-card#113]
Hi,

I am running the following Versions:

Home Assistant 2021.12.8
Valetudo 2022.01.0
lovelace-valetudo-map-card 2022.01.1

Since I upgraded my vaccum map is not shown anymore.

![image](https://user-images.githubusercontent.com/32883521/148200220-385e6d8e-83de-4956-bae5-056d88496999.png)

In my logviewer I have a huge Error-Message. As far as I understand it is my map in text.

I uploaded it to a pastebin-site, cause it is so huge: https://rentry.co/nof72

**Comment by TheLastProject** [comment]
Looking at the config, you probably did not follow the update instructions: https://github.com/TheLastProject/lovelace-valetudo-map-card/releases/tag/v2022.01.0

Feel free to comment if I'm wrong.

**Comment by mxwi** [comment]
I followed the update instructions. For control, I repeated it. Nothing changed.

**Comment by TheLastProject** [comment]
Are you sure? Because your vacuum still being named `valetudo_robot` makes no sense if you've been following the instructions.

Please show Configuration -> Devices -> MQTT -> Entities

**Comment by mxwi** [comment]
![image](https://user-images.githubusercontent.com/32883521/148204948-b3fbf8a1-35b5-4421-889a-3150d24ab878.png)

![image](https://user-images.githubusercontent.com/32883521/148204975-3881ddb6-1500-4aa2-ad4d-39aa0d9b89e5.png)

**Comment by TheLastProject** [comment]
What MQTT broker are you using?

**Comment by Hypfer** [comment]
Does the map data entity get previewed correctly when you click on it?

It should look like this:
![image](https://user-images.githubusercontent.com/974410/148208553-a73207ea-66b0-4370-bd39-e8e4acd294b0.png)

**Comment by mxwi** [comment]
> Does the map data entity get previewed correctly when you click on it?
> 
> It should look like this: ![image](https://user-images.githubusercontent.com/974410/148208553-a73207ea-66b0-4370-bd39-e8e4acd294b0.png)

yes, it does look like this.

I am using Mosquitto: https://github.com/home-assistant/addons/tree/master/mosquitto

**Comment by mxwi** [comment]
It works now. removed the mqtt config from configurations.yaml, restarted HA and pasted it back in. Now it works.
Can't explain what happended..
