### ISSUE TITLE
No map data

### ISSUE THREAD

**Issue by cradcore** [TheLastProject/lovelace-valetudo-map-card#114]
After adding the map card, I am getting no data from Valetudo:

![image](https://user-images.githubusercontent.com/21273406/148478053-22cb8377-24e2-475c-9e6b-486b3e2c5bb0.png)

Here is the raw yaml for the card:

```
type: custom:valetudo-map-card
vacuum: vacuum.valetudo_roborock_s7
title: Roborock Map
show_map: true
```

No error in my log. This is the first time I am installing this card, so not sure if I had to follow [the manual update steps](https://github.com/TheLastProject/lovelace-valetudo-map-card/releases/tag/v2022.01.0), but I did. No change however. 

Here are my MQTT (using Mosquitto as my broker) entities:
![image](https://user-images.githubusercontent.com/21273406/148480353-0ea0b649-ed91-4fc1-baef-30023adc551d.png)

and here is the MQTT settings in Valetudo:
![image](https://user-images.githubusercontent.com/21273406/148481793-4836909f-3b61-42b1-881b-05ab1386e6f4.png)

The camera entity does correctly show the "Please install and use the Lovelace Valetudo Map Card to display the map data embedded in this image"

I'm assuming its related to issue #113

Any idea what I could be missing or doing wrong?

**Comment by cradcore** [comment]
Just updated to the new version, and the error message is different, but still doesn't work:
![image](https://user-images.githubusercontent.com/21273406/148487688-7bda60ff-c574-44d6-b0ca-d7c352f4ef44.png)

**Comment by TheLastProject** [comment]
```
vacuum: vacuum.valetudo_roborock_s7
``|

This needs to be
```
vacuum: valetudo_roborock_s7
```

**Comment by cradcore** [comment]
Thank you! I figured it was something simple I was missing
