### ISSUE TITLE
MapCard does not show up in HA

### ISSUE THREAD

**Issue by KayGundhardt** [TheLastProject/lovelace-valetudo-map-card#115]
Hi everybody,

I rooted a Roborock S5 and S7 and installed valetudo (v2022.01.0) afterwards. Everything (including the map) works and shows up correctly in the robot’s own valetudo-webfrontend. Plus I made a connection to HA via my own private MQTT broker. MQTT-commands are alle executed correctly by both robots, only the map shows not up in HA (v2021.12.8). The Lovelace MapCard (v2022.01.2) was installed via HACS (v1.19.2). Have I missed out any manual setup in HA? Forgot something? Any Idea what goes wrong? Any help would be appreciated!

**Comment by TheLastProject** [comment]
So far, every time someone reported this issue it's been a caching issue: https://github.com/TheLastProject/lovelace-valetudo-map-card/issues/85#issuecomment-790248620

Please make absolutely sure it's not a caching issue. Like, repeat this like 20 times. I'm not kidding, Home Assistant's cache is ridiculously aggressive.

If you have confirmed it's not a caching issue feel free to reopen with the config and a screenshot of the exact error.

**Comment by mitsumaui** [comment]
Was about to say the same thing - was also just struggling, tried in another browser and it was fine. 
In Safari I just "Empty Caches" in the developer menu and all was good.

**Comment by KayGundhardt** [comment]
Although I already tested caching issues, just for you: installed a completely new browser (Firefox on Mac OS) plus I tried on a complete different OS (Linux with Opera) ob a machine never connected to HA-Webfrontend before. As expected: in both cases no map visible - just the info pic. What do you think? Is it safe to say that it is no cache issue?

**Comment by crunchhardtack** [comment]
Same problem here, also cleared cache many times and tried a different browser (never used with home assistant before). Still getting the error "Entity not available: camera.vacuum.rr_s5_map_data"

**Comment by arieltools** [comment]
> Same problem here, also cleared cache many times and tried a different browser (never used with home assistant before). Still getting the error "Entity not available: camera.vacuum.rr_s5_map_data"

remove "vacuum" prefix.
