### ISSUE TITLE
Entity not available: camera.undefined_map_data

### ISSUE THREAD

**Issue by Baggerfahrer** [TheLastProject/lovelace-valetudo-map-card#116]
Hey Guys,

i need some assistant regarding the proper installation of the valetudo-map-card.
Originally, it was working properly for months, but accidentally the card crashed some weeks ago, and i tried to solve it by myself without success.

I get the following error message when trying to activate the card in home-assistant.
![grafik](https://user-images.githubusercontent.com/25987294/150517452-ec7646b8-07e8-4fde-9bc7-1ea1a5f238cd.png)

My code looks like this:
`type: custom:valetudo-map-card
entity: camera.map_data
vacuum_entity: vacuum.robot
rotate: 0
crop:
  top: 0
  bottom: 0
  left: 0
  right: 0
min_height: 0
`
the code should be according to my knowledge fine, as it was working for months.

My robot entity is named like this:
![grafik](https://user-images.githubusercontent.com/25987294/150517624-c962ee5d-0bed-4cbe-a385-05a169ce25a7.png)

And the map data point is named like this:
![grafik](https://user-images.githubusercontent.com/25987294/150517705-0d237869-a9fe-4fc6-b69d-1545d1efa7ae.png)

I cannot see an error of the configuration?
Assistant would be highly appreciated.

Many thanks

**Comment by TheLastProject** [comment]
I didn't put all of this here for nothing:

![Screenshot 2022-01-21 at 12 17 42](https://user-images.githubusercontent.com/1885159/150518159-6b63decd-caec-4087-b795-2e78346e2bf2.png)

Read the release notes.
