### ISSUE TITLE
No map

### ISSUE THREAD

**Issue by CoveCompound** [TheLastProject/lovelace-valetudo-map-card#117]
I need to spend 25 hours a day to fix your issues. First I upgrade the map a couple of months ago only to find that I must first upgrade my valetudo version, so I downgrade to map version 11-25 and get used to denying your map upgrades, until I eventually get time to upgrade valetudo - which takes me 6 hours when I'm able to get around to it! And now your map still doesn't work, smh. I'm on the latest version of valetudo and the latest version of your map. I have no more time to give. Fix your crap.

**Comment by TheLastProject** [comment]
Fix your attitude. You have no right to demand things like this from someone who shares work they do for free in their spare time.
