### ISSUE TITLE
Custom element doesn't exist: valetudo-map-card.

### ISSUE THREAD

**Issue by DSDV** [TheLastProject/lovelace-valetudo-map-card#122]
Hi, 

i have: 
a fresh HAOS installation
with fresh HACS installed and configured.

i saw the picture that i should use this lovelace map card. 
- > after clicking around and finally googleing i found this github.

now following read me i ended up with the attached error :( 
![Capture](https://user-images.githubusercontent.com/5504857/174435033-4e14482f-d4da-4b84-8b9d-2008e5a7e122.JPG)

how to fix?

with kind regards

PS: i found mentioning here: https://community.home-assistant.io/t/valetudo-map-card-installation-instructions/247329/6 but i am not advanced enough to tinker with system resources

**Comment by tjhowse** [comment]
I also have this issue. I am running HASS 2022.6.6 in a docker container. I installed Lovelace Valetudo Map Card v2022.01.2 via HACS. I added
```yaml
      - type: custom:valetudo-map-card
        vacuum: valetudo_robbie
```
to my lovelace configuration and:

![image](https://user-images.githubusercontent.com/1008081/177003585-4da8981d-eb17-48cf-8402-cb44f89327f1.png)

shows up.

**Comment by DSDV** [comment]
currently it works for me. 

somewhere along the way i sem to have made a mistake. 
check your mqtt / integration with HACS etc. 

i can confirm it works now

**Comment by tjhowse** [comment]
I restarted hass after installing the addon via HACS and now it's working.
