### ISSUE TITLE
When robot is docked icon sould not be rotated

### ISSUE THREAD

**Issue by jacekpaszkowski** [TheLastProject/lovelace-valetudo-map-card#14]
Hi,

when robot is docked i think there sould not be any rotation of its icon. But now there is 90deg rotation.

Regards,
Jacek

**Comment by TheLastProject** [comment]
The rotation should be based on the last direction it drove in, is it not?

**Comment by jacekpaszkowski** [comment]
Hi, yes it looks that it depends on direction but i think robot icon would look better  without rotation when robot is docked :)

**Comment by TheLastProject** [comment]
It would look worse for me because then it would be "illogically rotated" for me. Because this change is so subjective and there's nothing really wrong with the current behaviour, I'm going to close this with a wontfix
