### ISSUE TITLE
Map doesn't load if no virtual walls are defined.

### ISSUE THREAD

**Issue by DarkFox** [TheLastProject/lovelace-valetudo-map-card#19]
If you haven't defined any virtual walls, the attribute is not added on the sensor, this causes this error when trying to load the map: `TypeError: mapData.attributes.virtual_walls is undefined`.

**Comment by TheLastProject** [comment]
Whoops, should be fixed in f2c2754985db61f14377ee1fc7ab45ef589d069b, thanks!
