### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dimensions' of undefined

### ISSUE THREAD

**Issue by Tri0L** [TheLastProject/lovelace-valetudo-map-card#21]
```
valetudo-map-card.js:257:49 Uncaught TypeError: Cannot read property 'dimensions' of undefine
```

How to diagnose it? How to understand what's wrong?

**Comment by TheLastProject** [comment]
What does your map entity look like?

http://your_home_assistant:8123/developer-tools/state and then search for whatever entity you used as map entity.

**Comment by TheLastProject** [comment]
Closing for lack of response, feel free to reopen when you have more info.
