### ISSUE TITLE
Map with controls and data?

### ISSUE THREAD

**Issue by jockebq** [TheLastProject/lovelace-valetudo-map-card#25]
The map works great! I love the ability to customize everything.
I did find this: https://macbury.github.io/SmartHouse/HomeAssistant/Vacuum/

<img width="529" alt="vacuum" src="https://user-images.githubusercontent.com/40036309/70302533-a4f66f80-17fd-11ea-8fc4-da484e91d12a.png">

Would it be possible to do something similar with this map? Adding controls and data, like battery on one single card?

**Comment by TheLastProject** [comment]
Oh, I somehow missed this issue. It would be cool, but I'll probably need help with this as I'm not that great with JavaScript

**Comment by TheLastProject** [comment]
I've added some controls in 5503b319aa95604e4b7302b825ffc4ef171d7b50. No data or so yet though and, well, I'm not a designer, so it doesn't look nearly as pretty.

**Comment by TheLastProject** [comment]
I've added some status elements in becff16cc9234b49ef0f42c881671f0f52e6c28b. Going to close this issue because well, there's both controls and data now. Feel free to open issues about more specific changes related to this, though!
