### ISSUE TITLE
Cropping is unintuitive

### ISSUE THREAD

**Issue by Dinth** [TheLastProject/lovelace-valetudo-map-card#26]
Is it possible to zoom a map?
Ive tried playing with map_scale parameter, setting it to 1.5 or 2 but it doesnt zoom.

**Comment by TheLastProject** [comment]
map_scale should zoom. Could you paste your whole configuration? Maybe you didn't indent it correctly?

**Comment by Dinth** [comment]
You're right, map_scale was intended to crop section. Thanks.
On another subject if i may, i have adjusted margins with crop top, left and map scale, but im getting a lot of white space underneath. When im trying to cut it off by increasing crop bottom, the whole image moves top and left, instead of whitespace getting cut.

**Comment by TheLastProject** [comment]
Yeah my cropping code kinda sucks, need someone to help improve that once :(

**Comment by Dinth** [comment]
Duplicate of https://github.com/TheLastProject/lovelace-valetudo-map-card/issues/3 i believe?

**Comment by TheLastProject** [comment]
Depends, do you also use rotation? If so, yes
