### ISSUE TITLE
Wrong colors?

### ISSUE THREAD

**Issue by fillilutten** [TheLastProject/lovelace-valetudo-map-card#27]
Are the colors supposed to look like this? 
https://imgur.com/a/ikI0M6R

I haven't added any color arguments. I saw you could change the floor color but can I change the background and wall color to make it look something like this?
https://imgur.com/a/WcOlJPl

I'm running latest ran256 fork.

Thanks!

**Comment by TheLastProject** [comment]
If your Home Assistant theme uses some green, then the colour scheme makes sense.

The floor colour is the background colour (the rest is purely the way your theme styles the card) and the wall in your case is probably `obstacle_strong_color`.

**Comment by fillilutten** [comment]
Aha of course, thanks! But there isn't a way to change the color of the box around around the actual map?

**Comment by TheLastProject** [comment]
Not supported no and I kinda feel it falls out of scope of this card as it's not specific to this card in any way. Try https://github.com/thomasloven/lovelace-card-mod?

**Comment by TheLastProject** [comment]
Going to close this in the hope the question is sufficiently answered, feel free to reopen
