### ISSUE TITLE
New "Angle" parameters

### ISSUE THREAD

**Issue by thelittlefireman** [TheLastProject/lovelace-valetudo-map-card#28]
Hi,
Could it be possible to add the "angle" parameter for the robot position and the charger position please ? (not just left and top position) see new commit for https://github.com/rand256/valetudo-mapper

[https://github.com/rand256/valetudo-mapper/commit/f9cb790d79d13ab835b437293d693ea5d863211b#diff-48cbac8e92e79592605d7d23cdbce639R37](https://github.com/rand256/valetudo-mapper/commit/f9cb790d79d13ab835b437293d693ea5d863211b#diff-48cbac8e92e79592605d7d23cdbce639R37)

Thanks a lot :)

**Comment by TheLastProject** [comment]
Are you sure this works?

When I look at it, the comment says it's "always 0":
https://github.com/rand256/valetudo-mapper/commit/f9cb790d79d13ab835b437293d693ea5d863211b#diff-48cbac8e92e79592605d7d23cdbce639R96

Also, I only see current_angle for the vacuum? And we already calculate the angle based on the last bit of direction it moved in this card.

**Comment by TheLastProject** [comment]
Over 3 months without any further info, so I'm closing this. Feel free to reopen if you have more info.
