### ISSUE TITLE
xiaomi_map state tab

### ISSUE THREAD

**Issue by jackkitley** [TheLastProject/lovelace-valetudo-map-card#29]
Hello

The xiaomi_map in states logs all the coordinates of the map. It causes the states to freeze up and i cant scroll.

Is there a way to solve this?

**Comment by TheLastProject** [comment]
Not solvable as far as I know because the map needs all those coordinates and Home Assistant doesn't want to hide anything

**Comment by jackkitley** [comment]
One more question:

i have that state map and i have a camera.rockrobo_map. i disabled the plugin for the map that generates so many coordinates and my states is fast now.

Im using camera.rockrobo_map which seems to do the same thing but looks different.

Is there a major difference?

**Comment by TheLastProject** [comment]
Currently, there isn't really a real difference except that lovelace-valetudo-map-card is more theme-able. In the future this card could be extended to do more, but right now, that's it.
