### ISSUE TITLE
Not working with Home Assistant 0.106

### ISSUE THREAD

**Issue by SBado** [TheLastProject/lovelace-valetudo-map-card#32]
With version 0.106 this card stops working. This is because starting from this version, the `config` object is no longer extensible ([see here](https://developers.home-assistant.io/blog/2020/02/18/106-custom-card-changes/#freeze-config)). A quick and dirty fix: add the following line at the very top of the `setConfig` method

`config = JSON.parse(JSON.stringify(config))`

Tested and working, but there may be other, more elegant solutions.

**Comment by TheLastProject** [comment]
Thanks for the report and clear info. Let me update first and check myself :)

**Comment by TheLastProject** [comment]
Weird, it isn't broken for me on 0.106 at all.

**Comment by TheLastProject** [comment]
Oh nvm I just didn't trigger it because I have every single setting defined.

**Comment by TheLastProject** [comment]
Fixed in c6c0589b440ab1099789ec31882c0ee8ea2243dd, again thanks for reporting, I would've missed it otherwise :)
