### ISSUE TITLE
Cannot add property show_dock, object is not extensible

### ISSUE THREAD

**Issue by littlerain14** [TheLastProject/lovelace-valetudo-map-card#33]
Hi,
I just updated Hassio to 0.106.1,

I got error at Lovelace UI

"Cannot add property show_dock, object is not extensible"

**Comment by TheLastProject** [comment]
Are you sure you're running the latest version of the card? This should've been fixed in c6c0589b440ab1099789ec31882c0ee8ea2243dd.

**Comment by littlerain14** [comment]
Ya, latest version is installed. 
I found that  need to clear cache to take effect :)
