### ISSUE TITLE
Problem add map home assistant core

### ISSUE THREAD

**Issue by roberdlv** [TheLastProject/lovelace-valetudo-map-card#36]
Hello friends, I have roborock s50, I installed Valetudo RE, it works in HA as MQTT, but the maps part does not work and I am not able to make it work, try this configuration:

I will try to put the steps that I have followed to see if I do something wrong or something is missing …

Copy the inside https://github.com/Poeschl/Hassio-Addons/tree/master/valetudo-mapper of this repository to / docker / homeassistant / custom_components / valetudo-mapper /

Config.json valetudo-mapper:

{
“mqtt”: {
“identifier”: “rockrobo”,
“topicPrefix”: “valetudo”,
“autoconfPrefix”: “homeassistant”,
“broker_url”: “mqtt: // admin: pass@192.168.1.2: 1883”,
“caPath”: “”,
“mapSettings”: {
“drawPath”: true,
“drawCharger”: true,
“drawRobot”: true,
“drawForbiddenZones”: true,
“drawVirtualWalls”: true,
“border”: 2,
“scale”: 4,
“gradientBackground”: true
},
“mapDataTopic”: “valetudo / rockrobo / map_data”,
“minMillisecondsBetweenMapUpdates”: 10000,
“publishMapImage”: true,
“publishMapData”: true
}
}

config.json roborock:

root @ rockrobo: / mnt / data / valetudo # nano config.json
GNU nano 2.2.6 File: config.json

{
“spots”: [],
“areas”: [],
“ztimers”: [],
“mqtt”: {
“enabled”: true,
“identifier”: “rockrobo”,
“topicPrefix”: “valetudo”,
“autoconfPrefix”: “homeassistant”,
“broker_url”: “mqtt: // admin: pass@192.168.1.2”,
“provideMapData”: true,
“mapSettings”: {
“drawPath”: true,
“drawCharger”: true,
“drawRobot”: true,
“border”: 2,
“scale”: 4
},
“caPath”: “”

Configuration.yaml

discovery: true
discovery_prefix: homeassistant

sensor:

platform: mqtt
state_topic: “valetudo / rockrobo / state”
json_attributes_topic: “valetudo / rockrobo / map_data_parsed”
name: xiaomi_map
value_template: ‘OK’
scan_interval: 5
remember:
exclude:
entities:
- sensor.xiaomi_map

I add custom card:

crop:
bottom: 0
left: 0
right: 0
top: 0
entity: sensor.xiaomi_map
min_height: 0
rotate: 0
type: ‘custom: valetudo-map-card’

I tried to create docker but it gives exec error user process caused “exec format error”
I use Portainer and docker from:

Pure Home Assistant (not HASSIO)
MQTT
PORTAINER
etc…

**Comment by TheLastProject** [comment]
Please put your JSON and YAML code between three ` symbols above and below each bit of code. Especially in YAML the indentation matter and I can't judge the YAML code well this way.

**Comment by roberdlv** [comment]
the problem is that i can't add valetudo mapper to my pure home assistant (i don't have hasio) so i can't see the map ....

**Comment by TheLastProject** [comment]
I really can't help much because your code isn't readable but "exec format error" normally means you're trying to run a container made for another architecture (like an arm container on x64 or the other way around). So that error is completely unrelated to this project.

**Comment by roberdlv** [comment]
I am following the instructions of this repository, but in the section of adding maps with valetudo mapper they are disastrous and I am unable to make it work ... I have raspberry pi 4, what command or how should I mount the docker for valetudo mapper?
