### ISSUE TITLE
add pause button

### ISSUE THREAD

**Issue by lukich48** [TheLastProject/lovelace-valetudo-map-card#39]
Hello ). It would be good to add a pause button. When I use zoned cleanup (always) stop button definitely erase my map. I have Xiaomi vacuum 1s

**Comment by TheLastProject** [comment]
I have a bit too many projects, so I want to nudge people to contribute themselves especially on these easy things so I don't do everything myself :)

Look at https://github.com/TheLastProject/lovelace-valetudo-map-card/blob/fe6f01fc8fa67a4305bed9eb464783f1bea268c1/valetudo-map-card.js#L441-L462 for the code for the start and stop button. Adding a pause button should be very simple, just copy the start or stop code and change the names to pause.

I'll probably do it myself eventually if nobody beats me to it, but consider this a kind request to help yourself if you can :)

**Comment by lukich48** [comment]
Ok. I think I can do this :)

**Comment by TheLastProject** [comment]
Fixed in #41, thanks again!
