### ISSUE TITLE
Location icon of vacuum did not change in 0.110

### ISSUE THREAD

**Issue by murmelbahn** [TheLastProject/lovelace-valetudo-map-card#44]
Hi,
after installation 0.110 the icon of the  vacuum didn't move over the map. It is stucked at left upper corner during movement of the robot. The Path of the robot is visible. Here a screenshot of my map:

<img width="399" alt="grafik" src="https://user-images.githubusercontent.com/19727146/82538030-5f2f2880-9b4b-11ea-8012-0bf63b1f0da8.png">

**Comment by cyberoida** [comment]
Since 0.110, icons are generally missing from my card:
![image](https://user-images.githubusercontent.com/57094912/82565146-383c1b00-9b7a-11ea-85fe-7f2a500ace01.png)

Since the robot itself is also just an icon (mdi:robot-vacuum I think) maybe this is related?

**Comment by TheLastProject** [comment]
@murmelbahn Thanks for the report, fixed in 9cfe1add100ab27765aefe5f4f5c59686d2b4b78.

@cyberoida I honestly don't really understand your screenshot. If this commit doesn't fix the issue for you, could you please create a new issue with more info and output from your browser console?

**Comment by murmelbahn** [comment]
@cyberoida you are referring to the vacuum card. there is a fix for this already but this has nothing to do with the valetudo map card;)
