### ISSUE TITLE
No way to display active zone cleaning at map

### ISSUE THREAD

**Issue by CODeRUS** [TheLastProject/lovelace-valetudo-map-card#47]
Hi!

I'm looking for option to draw zone rectangle on map when cleaning in process, like in original valetudo map

Valetudo:
![изображение](https://user-images.githubusercontent.com/720601/83953004-9e48c380-a845-11ea-9f41-06b1c765a7a5.png)

Map card:
![изображение](https://user-images.githubusercontent.com/720601/83953010-ab65b280-a845-11ea-8d76-f08bd5420482.png)

**Comment by TheLastProject** [comment]
Oh, interesting. I never used zoned cleanups myself, so I didn't know that was a feature.

A note for my own information when I get to implementing this (or for whoever may beat me to it):
While a zoned cleanup is done, the map JSON contains the following data:
```
currently_cleaned_zones: 
- - 27001
  - 23000
  - 30451
  - 20700
```

This data is on the same depth and uses the same numbering system as no_go_areas do, so that code can be almost completely used as-is, just with other default theming.

**Comment by TheLastProject** [comment]
Fixed in f976ffc3caa7b7cca4193766d8c3206ef5efee74. Not as pretty though, I made #48 for that to fix that later.

**Comment by CODeRUS** [comment]
almost LGTM, can you show it only when clean is active?

**Comment by TheLastProject** [comment]
I'll look at that later, I'll have to combine the vacuum_entity info with the (map) entity info, as the map itself contains no state. Need to think of how I want to do that, but I understand the desire for that

**Comment by CODeRUS** [comment]
For myself i just want consistency how own valetudo map behaves and this map card.

**Comment by TheLastProject** [comment]
It is consistent now though? Valetudo's built-in map also keeps showing the last zone even after cleaning is done.

**Comment by CODeRUS** [comment]
I'm using RE version and it's not displaying last cleaned zone after cleaning is finished and vacuum is docked.

**Comment by TheLastProject** [comment]
Hmm, different behaviour between Valetudo and RE. That's a bit of an... interesting thing to deal with...

**Comment by TheLastProject** [comment]
Seeing how Valetudo RE just steals code from Valetudo without attribution: https://github.com/rand256/valetudo/commit/15415e842d5b2004a836744a204f34b003d58e19 (seriously, half this code is mine, that's really not cool) I'm going to close this and use the following policy whenever Valetudo and Valetudo RE differ: Follow Valetudo.

So, won't fix.

**Comment by CODeRUS** [comment]
why so? even if original valetudo doing it differently, an option to show zone brushes only when active cleaning would be cool

**Comment by CODeRUS** [comment]
also seems you pasted link to wrong commit
