### ISSUE TITLE
Render map image to file for external usage

### ISSUE THREAD

**Issue by markusressel** [TheLastProject/lovelace-valetudo-map-card#54]
Hi there, great project :+1: 

A while ago I used the image renderer of Valetudo and its REST API to display the map in Home Assistant. Since then, this card has replaced it, since it is much more versatile.

However, afaik, it is currently not possible to use the rendered map image from this custom component as a notification image. To allow this I would be interested in a way to render the map not only in the browser, but also to a file, possibly using a customized homeassistant service call. That way the image file can be used by other services, like f.ex. a notify service.

I am not sure if this lovelace component is the right place to ask for this, so feel free to guide me to other places if necessary.
Thx

**Comment by TheLastProject** [comment]
I don't know of any way to do this at all. But I will leave this open in case someone else does because the idea itself is not that bad

**Comment by infinity312** [comment]
It's relatively straightforward modify this card to support what you're describing but I don't think you'd want to since the rendered image would only be updated if your browser was open to the HA page.  I would think that this feature should probably be implemented as an integration instead of a card.

**Comment by TheLastProject** [comment]
Good point. Would probably be better to use https://github.com/Hypfer/ICantBelieveItsNotValetudo for this.
