### ISSUE TITLE
Valetudo 0.6.0 support

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/lovelace-valetudo-map-card#55]
New map format will need a lot of rewriting

- [x] Charger location
- [x] Robot location
- [x] Floor
- [x] Walls
- [x] Path
- [x] No go areas
- [x] Virtual walls
- [ ] Active zones (previously: currently_cleaned_zones)

**Comment by TheLastProject** [comment]
Seems like I got it working! Please test!

The code is in https://github.com/TheLastProject/lovelace-valetudo-map-card/tree/feature/0.6-compat, replace your valetudo-map-card.js in `www/community/lovelace-valetudo-map-card` in your Home Assistant directory with the .js file in that branch. Make sure to delete the .gz file that may be in that directory!

Please test and tell me how it works for you. If you still have a Valetudo version before 0.6, please test as well so I can be sure I didn't break anything for people who haven't upgraded yet!

**Comment by darootler** [comment]
I am using the REST sensor, for me it's not working. Is there anything to change for the sensor to work?

Regards
Richard

**Comment by TheLastProject** [comment]
@darootler Did you use this card before? I really only want to debug my 0.6 parsing here, not the REST stuff. REST is listed as unsupported in the README because @Hypfer clearly told me it's not supported.

**Comment by darootler** [comment]
Yes, i used this card before with the rest sensor. I didn't want to setup mqtt just for having the map.

Regards
Richard

**Comment by infinity312** [comment]
It's working for me with 0.6.0 but it's slightly shifted toward the bottom of the card.

**Comment by TheLastProject** [comment]
Well, no obvious big issues left it seems. Let's just push this live and see what complaints I'll have to deal with from pre-0.6 users tomorrow :)
