### ISSUE TITLE
MQTT with hostname not working

### ISSUE THREAD

**Issue by darootler** [TheLastProject/lovelace-valetudo-map-card#59]
I have the following configuration working:

>  "mqtt": {
>     "enabled": true,
>     "server": "192.168.X.X",
>     "port": 1883,
>     "clientId": "",
>     "username": "myuser",
>     "password": "myasswd",
>     "usetls": false,
>     "caPath": "/mnt/data/valetudo/ca.pem",
>     "qos": 0,
>     "identifier": "abstellraum-staubsauger",
>     "topicPrefix": "valetudo",
>     "autoconfPrefix": "homeassistant",
>     "provideMapData": true
>   },

This configuration is not working:

>  "mqtt": {
>     "enabled": true,
>     "server": "mqtthost.my.domain",
>     "port": 1883,
>     "clientId": "",
>     "username": "myuser",
>     "password": "myasswd",
>     "usetls": false,
>     "caPath": "/mnt/data/valetudo/ca.pem",
>     "qos": 0,
>     "identifier": "abstellraum-staubsauger",
>     "topicPrefix": "valetudo",
>     "autoconfPrefix": "homeassistant",
>     "provideMapData": true
>   },

Can someone point in the right direction how to get this working with the hostname set? I am able to ping the hostname from the vacuum command line.

Regards
Richard

**Comment by TheLastProject** [comment]
That's not part of the card's configuration, but of Valetudo, so clearly not related to the card. Please report the issue to Valetudo: https://github.com/Hypfer/Valetudo/issues.

**Comment by darootler** [comment]
Sorry, i posted this issue in the false github repo.

Regards
Richard
