### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by talondnb** [TheLastProject/lovelace-valetudo-map-card#6]
I've been running this on a Pi 3B and it seems that this card chews through memory quite rapidly? I noticed the memory usage in my system monitor was at 146MB but within a few minutes was down to 44MB and now I can no longer access the web GUI and the Pi will need a reboot.

Anyone else experience this?

**Comment by TheLastProject** [comment]
I'm not a Javascript developer, so I don't quite know what I'm doing (just trying stuff until it works), so it's very possible I did something bad somewhere. I'm hoping 0f431a654f00a96635fdc07bf0603c185e9f6571 may help improve the issue a bit though.

**Comment by TheLastProject** [comment]
I'm going to close this due to lack of response and the issue report itself being too vague to really be able to do anything about. If the issue remains and you can pinpoint the issue down more, please reopen

**Comment by benjamfk** [comment]
I noticed the same thing. It's killing my PI3b+ when I have two vacuums running at the same time (Mosquitto MQTT).
