### ISSUE TITLE
map_scale is broken for 0.6.1

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/lovelace-valetudo-map-card#66]
It only scales the container, not the actual map.

**Comment by OzGav** [comment]
I am seeing the map scaled but it is being pushed off the bottom and left of the container? First is map scale 1 then map scale 0.75. I am thinking there is an error in the offset calculations?

![valetudo_map2](https://user-images.githubusercontent.com/19848947/95041984-afcea900-071b-11eb-937d-37871b5c36c3.jpg)

This is with a rotation of 90.

![valetudo_map](https://user-images.githubusercontent.com/19848947/95041788-130c0b80-071b-11eb-9815-61571ba77281.jpg)

**Comment by jkmf** [comment]
#74

**Comment by TheLastProject** [comment]
Fixed in 19248b5b8d5a7bd72cb6009f3462cd8044a396dd
