### ISSUE TITLE
Error add a Card

### ISSUE THREAD

**Issue by barcelona92** [TheLastProject/lovelace-valetudo-map-card#71]
When add a card. is not possible:

Add:
type: 'custom:valetudo-map-card'

error:
Error: Custom element not found: valetudo-map-card

Any idea, i installed with HACS and all ok.

**Comment by TheLastProject** [comment]
Did you check #68 and confirmed that the steps in there didn't work? That is about the exact same issue after all.

**Comment by barcelona92** [comment]
appear these error:

Entity not available: sensor.xiaomi_map

**Comment by TheLastProject** [comment]
Did you follow the instructions in the README?

**Comment by barcelona92** [comment]
Appear error in log:

Can't decode payload b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x03\xed\x9d\x07|\x13e\x1f\x80\x13\x14Y\xb2\x04\\\xc8\x14\xd9\xb2\x04\x99\xb2\xb3JK\xdb4i\x9a\\\xc6\xdd\xbd7\xb3\x93\xe6\xee\xb2\xda2d\x0b\x8a\xa0\xb2\x97\xc8T\xd9 K\xa6\xb2AP\x90\r\n\xea\'K\x99\xb2\xfbEhKG\xd26\x9dP\xef\xe1w\xa4Y7\xfe\xcf\xbd\xfb\xbd\x8b\xd3Y[\xd0\xa5o9\x81P \x10\xb4\xac x\xf4XN\xf0\xaa\xa0\xcb+\xe5\x04\xef\x07\x9e<\x0c<\xd7\x04\x1e?\xf8\xf7\r\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x1e\x9e"%5\xf0\x8f\xe7\xa9\x80W\xc1\xc3\xc3\xf3\x14\xc3gPO\rOJ\x0b^J\xe9\x92\xfaXA\xfa\xc2S\xaa\xf0\n\x9e\x0ex\x0fO\x0f\xa99\xfe\xe0)%RSS\x1f\xfd\x0e\x0b\xaf\xa2\xf4I\xe5-<5\xa4\x06\xf9\x8b\xa74\x08dP\xa9\xa9|u\xb6\xb4I}\xfc_\x9a\r\x9e\xd2\xe5\x91\x06\xbe\x83\xf6i
x9f\xc8Q+\xae\x1e\xfa?q8@*LB\x02\x00' on valetudo/rockrobo/map_data with encoding utf-8 (for <function MqttAttributes._attributes_subscribe_topics.<locals>.attributes_message_received at 0x7f51b1790>)

**Comment by TheLastProject** [comment]
What Valetudo version are you running?

**Comment by barcelona92** [comment]
Valetudo RE   v.0.9.6

**Comment by TheLastProject** [comment]
RE is not officially reported but you may be able to get it to work in legacy mode: https://github.com/TheLastProject/lovelace-valetudo-map-card/commit/9f7706f8715d984c1d293ad8b2059841842a01db
