### ISSUE TITLE
Can't install??

### ISSUE THREAD

**Issue by TheConsciousness** [TheLastProject/lovelace-valetudo-map-card#79]
Would anyone be able to help? I'm trying to install this guy, but am not sure why I would without any pictures of the product first.

**Comment by TheLastProject** [comment]
There are various screenshots in GitHub issues but no official ones because I'm not really interested in sharing pictures of my home's layout. Contributions welcome though.

As for the help, where are you stuck?

**Comment by reptilex** [comment]
Well I'm stuck not finding valetudo in HACS at all.
