### ISSUE TITLE
Test 2021.01.1

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/lovelace-valetudo-map-card#80]
2021.01.1 has a lot of changes. Needs to be tested and probably some stuff fixed.

Please report all issues with running Valetudo 2021.01.1 because I will surely miss some things.

**Comment by kquinsland** [comment]
I just did the upgrade and managed to pull one of the messages from my MQTT broker. I have not tested the custom components you  link to in the readme, but was curious about  what's in the new payload format...

```python3
import zlib
import base64
import json
import pprint

pp = pprint.PrettyPrinter(indent=4)

with open('map.raw', 'r') as raw:
    _raw = raw.read()
    _data = base64.b64decode(_raw)
    _map_data_str = zlib.decompress(_data).decode("utf-8")

    _map_data_obj = json.loads(_map_data_str)

    #print(f"_map: {_map_data}")

    print(f"_map_data_obj has {len(_map_data_obj)} keys: {_map_data_obj.keys()}")

    for k in _map_data_obj.keys():
        #  'layers', 'entities' are the two obj w/ a TON of data in them...
        if k not in ['layers', 'entities']:
            print(f"KEY: '{k}' is: {_map_data_obj[k]}")
        else:
            for l in _map_data_obj[k]:
                _class = l['__class']
                if _class == 'MapLayer':
                    print(f"layer for {l['type']} has {len(l['pixels'])} points covering {l['metaData']['area']} units of area")
                if _class == 'PathMapEntity':
                    print(f"PATH has {len(l['points'])} points ...")
                if _class == 'PointMapEntity':
                    print(f"The {l['type']} is located at {l['points']}")
                if _class == 'PolygonMapEntity':
                    print(f"The {l['type']} is represented by {len(l['points'])} points...")
    with open('map.json ', 'w') as map_json:
        map_json.write(_map_data_str)

```

which produces:

```shell
$ python3 test.py  
_map_data_obj has 6 keys: dict_keys(['__class', 'metaData', 'size', 'pixelSize', 'layers', 'entities'])
KEY: '__class' is: ValetudoMap
KEY: 'metaData' is: {'version': 1}
KEY: 'size' is: {'x': 5120, 'y': 5120}
KEY: 'pixelSize' is: 5
layer for floor has 40460 points covering 505750 units of area
layer for wall has 3640 points covering 45500 units of area
layer for segment has 23896 points covering 298700 units of area
layer for segment has 10696 points covering 133700 units of area
layer for segment has 3568 points covering 44600 units of area
PATH has 474 points ...
The charger_location is located at [3053, 2199]
The robot_position is located at [3050, 2216]
The active_zone is represented by 8 points...
```

I dont want to put the full JSON obj here, but am more than happy to share it privately.

**Comment by TheLastProject** [comment]
Oh, interesting metaData version is still 1. Either that means that nothing has changed so it should still be 100% compatible or @Hypfer forgot to change the version info. Let's hope the first one. Feel free to send me the full JSON to whichever method you prefer listed on https://hackerchick.me/#contact :)

**Comment by kquinsland** [comment]
Thanks for the super fast reply @TheLastProject .  I sent you an email. Subject is `TheLastProject/lovelace-valetudo-map-card`

**Comment by TheLastProject** [comment]
I loaded in the JSON and awesome news! The map card still works for 2021.01.1 it seems! :) I'll close this issue for now because it is tested. Can reopen if any specific issues are found :)

**Comment by Hypfer** [comment]
The only difference should be the deflate/inflate & base64encode/decode part. The payload itself is the same.

There's a new type of zone: The no-mop-zone.
https://github.com/Hypfer/Valetudo/blob/852683b25815a05235b580a313a2464714786f4c/lib/entities/map/PolygonMapEntity.js#L21-L24

It's currently still impossible to create them using Valetudo but they will appear soon-ish. Should that be a version increment? 🤔

**Comment by kquinsland** [comment]
@Hypfer Thanks you  for all of your work and for clarifying that the transport/encoding method is the only change. As the data structures didn't change, I would argue that it's not a version bump. FTP versus FTP over TLS, for example...

Introducing a new field or a structure would warrant a version bump, though.
