### ISSUE TITLE
Entity not available: sensor.myVac_valetudo_map even with `decode_valetudo_map` filter.

### ISSUE THREAD

**Issue by kquinsland** [TheLastProject/lovelace-valetudo-map-card#81]
Entity not available: sensor.myVac_valetudo_map

I get this error when I try to display the map card.
I first thought this was related to the new 2021.01 release of Valetudo, but even after adjusting my template sensor to use the `decode_valetudo_map` filter, the message is still present.

Here's the mqtt sensor:

```yaml
# See https://github.com/TheLastProject/lovelace-valetudo-map-card
- platform: mqtt
  name: myVac_valetudo_map
  state_topic: "valetudo/myVac/map_data"
  value_template: "OK"
  json_attributes_template: "{{ value | decode_valetudo_map }}"
```

Before using the custom_filters but after the valetudo upgrade, i'd see errors in my home assistant log about inability to decode the payload (b64 data). I no longer see the errors, so I'm assuming that the `decode_valetudo_map` filter is being invoked but beyond that, i'm stuck.

If i pull a sample payload from the `valetudo/myVac/map_data` topic and manually feed it into the `template` section of developer tools, I see what looks like the correct data:

```
{% set value = "eJxc3UGvHE1+5efv0uteVEbEOf8orb20Vwa88cJo2DIwgOwZjGRjxgN/d4u8T7IbXhA5r4Z6KDDzBMm6v6r73/7yv/wv/+u//O1f//Uv//SX/+lv//<...>uOfYvDnLr+vmKl8efj2/vvj7++vzLF3z5++Pj+TcWr6PLSRg0qpbCWxn/pvvpz/fqTrx3/zyeP7z5/vb7D7hmeE8=" %}

json_attributes_template: "{{ value | decode_valetudo_map }}"

```

Produces this output:

```
json_attributes_template: "{"__class":"ValetudoMap","metaData":{"version":1},"size":{"x":5120,"y":5120},"pixelSize":5,"layers":[{"__class":"MapLayer","metaData":{"area":508925},"type":"floor","pixels":[491,519,492,519,493,519,494,519,495,519,496,519,497,519,< ... > 7,3048,2233,3049,2227,3050,2225,3050,2222,3051,2219,3051,2218],"type":"path"},{"__class":"PointMapEntity","metaData":{},"points":[3053,2200],"type":"charger_location"},{"__class":"PointMapEntity","metaData":{"angle":8},"points":[3051,2217],"type":"robot_position"},{"__class":"PolygonMapEntity","metaData":{},"points":[2813,2564,2813,2184,3204,2184,3204,2564],"type":"active_zone"}]}"
```

I'm not sure where else to look for logs / debug information. There's nothing specific in the web browsers console, either; just a few warnings like:

```
The resource at “https://ha.internal.com/frontend_latest/app.645d69e3.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.
```

Under the `states` section of developer tools, this is all I see under `attributes`:

```
friendly_name: myVac_valetudo_map
```

Thoughts?

**Comment by TheLastProject** [comment]
Your MQTT sensor doesn't seem to match the README example? What happens if you try this?

```
- platform: mqtt
  name: myVac_valetudo_map
  state_topic: "valetudo/myVac/state"
  json_attributes_topic: "valetudo/myVac/map_data"
  value_template: "OK"
  json_attributes_template: "{{ value | decode_valetudo_map }}"
```

**Comment by kquinsland** [comment]
> Your MQTT sensor doesn't seem to match the README example? What happens if you try this?

Initially, it did. I was playing around w/ the definition trying to see if I could tease out any error/warn from the HA logs.

I restored the config to mirror the README and still no luck.
I don't understand _why_ but this worked:

1. Update the config, add a `_new` suffix to name
2. reload HA config
3. edit the dashboard to refer to the new entity
4. *works*
5. Revert the config to remove the `_new` suffix
6. revert the config change to lovelace dashboard
7. reload HA
8. *works*
