### ISSUE TITLE
Entity not available: camera.map

### ISSUE THREAD

**Issue by exotsk** [TheLastProject/lovelace-valetudo-map-card#86]
Valeudo lastest dev 2021.2+, lovelace-valetudo-map-card latest release.
**lovelace-valetudo-map-card** - installed by hacs. all entities is on the places.

![image](https://user-images.githubusercontent.com/54969124/109967038-84300900-7d23-11eb-8c66-8572c53baa25.png)

![image](https://user-images.githubusercontent.com/54969124/109965597-bfc9d380-7d21-11eb-8e73-487e020c2ac3.png)
![image](https://user-images.githubusercontent.com/54969124/109965657-d839ee00-7d21-11eb-985b-10179b951f9a.png)

If enable homeassistant hack i have white text picture. In node-red, valetudo node convert mqtt sucsessfuly.
![image](https://user-images.githubusercontent.com/54969124/109966036-5bf3da80-7d22-11eb-9a2d-7dbcfc533a65.png)
where i can make a mistake?

**Comment by TheLastProject** [comment]
The home assistant map hack is necessary for the card to work. The card directly reads the data embedded in the PNG file, so you don't need node red. What is exactly going wrong when you use the home assistant map hack?

**Comment by exotsk** [comment]
is apperad after toggle hass hack in options and chnging any  digits in setting off card, crop or rotate

**Comment by TheLastProject** [comment]
So, sounds like you got it working then? I'll close this issue then. Please respond if I misunderstood you

**Comment by exotsk** [comment]
yes, it`s working now. thank you
