### ISSUE TITLE
floor_color just stacks over original floor color from Valetudo

### ISSUE THREAD

**Issue by Jaytie2k7** [TheLastProject/lovelace-valetudo-map-card#87]
Hi! Great Card!
I'm having an issue with changing the floor color.
The color I set via 'floor_color' changes the floor color correctly, but on top of that are displayed the colors of (in my case) two segments. 
Maybe thats more an issue for the valetudo github page, as I did not find out a way to disable the segments or change the color of the segments in valetudo.

`type: 'custom:valetudo-map-card'
title: Robobert
entity: camera.map
vacuum_entity: vacuum.robobert
rotate: 0
crop:
  top: 0
  bottom: 0
  left: 0
  right: 0
min_height: 0
show_floor: true
background_color: '#1a1a1a'
floor_color: '#1a1a1a'
floor_opacity: 1`

floor_color set to white
![white](https://user-images.githubusercontent.com/63009998/109973305-8892fc80-7cf8-11eb-90cc-2e76a56657c7.JPG)

Original color:
![original](https://user-images.githubusercontent.com/63009998/109973352-95175500-7cf8-11eb-89e7-b8bd760ea15f.JPG)

Running Valetudo 2021.02.0

**Comment by TheLastProject** [comment]
Could you try setting segment_opacity to 0?

**Comment by Jaytie2k7** [comment]
Wow, how could I overlook this?
That works! Thanks and sorry :)

**Comment by TheLastProject** [comment]
It's easy to overlook, there's... a bit many options. And for some reason not all options have show_* variables.

It would probably be best for someone to make sure every option has a show_* variable and then reorganize the README so it's easier to find these things.

But for now, helping someone every now and then works :)
