### ISSUE TITLE
"Please install custome custome lovelace map" issue

### ISSUE THREAD

**Issue by Kaan88** [TheLastProject/lovelace-valetudo-map-card#96]
Hi, map works fine If I add it myself manually but it won't work properly on the main page where it's added automatically. Any ideas?

![image](https://user-images.githubusercontent.com/1260152/132484201-34fd6049-1b6b-4290-b2fa-8ea3ed6bfb72.png)

**Comment by TheLastProject** [comment]
That screenshot is not from the Lovelace Valetudo Map Card. You can't use another card and expect it to work. You need to use the Lovelace Valetudo Map Card.
