### ISSUE TITLE
How to create a custom button

### ISSUE THREAD

**Issue by jonathanleinola** [TheLastProject/lovelace-valetudo-map-card#99]
Hi,

I am trying to figure out how could i automate a task "clean a zone" and then stop. So that i could empty the trash bin and sent the robot back to home.

Is that possible via custom button? If yes, how can i do that?

Kindly,
Jonathan

**Comment by fpschrisiom** [comment]
Just to add to this for others, here's my example for multiple buttons

`custom_buttons:
  - service: script.clean_dining_room
    icon: mdi:table-chair
  - service: script.clean_dining_room
    icon: mdi:sofa
  - service: script.clean_living_room
    icon: mdi:stove
  - service: script.clean_kitchen
    icon: mdi:stairs
  - service: script.clean_landing
    icon: mdi:toilet
  - service: script.clean_toilet
    icon: mdi:bed-king
  - service: script.clean_master_bedroom
    icon: mdi:shower
  - service: `script.clean_master_bathroom`

and here's my background script

`#Clean Dining Room
clean_dining_room:
  alias: "Dr Robotnick Clean Dining Room"
  sequence:
    - service: mqtt.publish
      data:
        topic: valetudo/robot/ZoneCleaningCapability/start/set
        payload: "[\"ID_OF_ROOM_HERE\"]"`

In my configuration.yaml I have this line to point to my scripts.yaml

`script: !include scripts.yaml`
